redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development: *redis

test: *redis

staging: *redis
  url: <%= ENV.fetch("REDISTOGO_URL") %>

production: *redis
  url: <%= ENV.fetch("REDISTOGO_URL") %>
